spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: Nagare@2020
  application:
    name: cibil-score-service
    
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    
    
server:
  port: 2020
  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
  
